- name: "Set up service {{app_name}} on kamatera"
  vars_files:
    - vars/prod.yml
  gather_facts: no
  hosts: kamatera
  remote_user: "{{remote_admin}}"
  become: true
  become_method: sudo
  tasks:
    - name: "Creating user {{app_name}}"
      user:
        name: "{{app_name}}"
        shell: /bin/bash
        create_home: yes
        password: "{{user_password | password_hash('sha512') }}"
        state: present
    - name: "Create folder app in {{app_name}} home folder"
      file:
        path: "/home/{{app_name}}/app"
        state: directory
        owner: "{{app_name}}"
        group: "{{app_name}}"
        mode: '0700'
    - name: Copy application to app folder
      copy:
        src: "../../target/{{app_name}}-{{app_version}}.jar"
        dest: "/home/{{app_name}}/app/{{app_name}}-{{app_version}}.jar"
        owner: "{{app_name}}"
        group: "{{app_name}}"
    - name: Copy prod.env to app folder
      copy:
        src: ../../env/prod.env
        dest: "/home/{{app_name}}/app/"
        owner: "{{app_name}}"
        group: "{{app_name}}"
    - name: "Copy systemd service-template.service config file to /etc/systemd/system folder"
      template:
        src: data/service-template.service
        dest: "/etc/systemd/system/{{app_name}}.service"
        owner: root
        group: root
    - name: Reload systemd
      systemd:
        daemon_reload: yes
    - name: "Restart service {{app_name}}"
      systemd:
        state: restarted
        name: "{{app_name}}"
