server.port=12000
server.ssl.enabled=true
server.ssl.key-store=/home/radar-collector/app/keystore.p12
server.ssl.key-store-password=
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=radar-collector
server.ssl.client-auth=none
server.ssl.enabled-protocols=TLSv1.3,TLSv1.2

