spring.application.name=radar-collector
spring.threads.virtual.enabled=true

# RabbitMQ connection settings (required).
spring.rabbitmq.host=
spring.rabbitmq.port=
spring.rabbitmq.username=
spring.rabbitmq.password=
